### ISSUE TITLE
Usage pattern discussion

### ISSUE THREAD

**Issue by geyang** [escherpad/scala_spark_ot#3]
@jiamingguo @jam-world 

### TODOs
- [x] take a look at the pattern below, and fill in the pattern you think is appropriate for 
    - [ ] array type
    - [ ] object type
- [x] then reorganize the folder accordinly (in a new PR after current ot-test branch is closed)
- [ ] change the diff format as well

I am attempted to have the library use the following pattern:

### ot-reducers
```js
import {reducer} from 'ot/string';

reducer('Mary has a little lamb.', {ot: [5, 4]}); // 'Mary a little lamb.'
```
### applying operations
```js
import {apply} from 'ot/string';

apply('Mary has a little lamb.', [23, " Bob is awesome"]);// 'Mary ... Bot ... awesome'
apply('Mary has a little lamb.', [0, 4]);// 'has a little lamb';
apply('Mary has a little lamb.', [0, [5, 17]]);// 'has a little Mary lamb';
```
### transforms
```js
import {transform} from 'ot/string';

transform('Mary ', [0, 5], [2, 'r']); // [0, 'r']
```

**Comment by jiamingguo** [comment]
aaaaaaaaa
